openapi: 3.0.2
info:
  title: EnamDua App
  version: "1.0"
servers:
  - url: http://localhost:8000/api
paths:
  /business/search:
    get:
      tags:
        - Business
      summary: List Business
      parameters:
        - in: query
          name: page
          description: Page
          required: false
          schema:
            type: integer
        - in: query
          name: price_range
          description: Price range by select box
          required: false
          schema:
            type: number
        - in: query
          name: sort
          description: Sort Price Order
          required: false
          schema:
            type: string
        - in: query
          name: limit
          description: Limit Per Page
          required: false
          schema:
            type: number
      description: List Business
      responses:
        "200":
          description: List Business
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        alias:
                          type: string
                        categories:
                          type: array
                          items:
                            type: object
                            properties:
                              alias:
                                type: string
                              title:
                                type: string
                        coordinates:
                          type: object
                          properties:
                            latitude:
                              type: number
                            longitude:
                              type: number
                        display_phone:
                          type: string
                        distance:
                          type: number
                        image_url:
                          type: string
                        is_closed:
                          type: boolean
                        location:
                          type: object
                          properties:
                            address1:
                              type: string
                            address2:
                              type: string
                            address3:
                              type: string
                            city:
                              type: string
                            country:
                              type: string
                            state:
                              type: string
                            zip_code:
                              type: string
                        display_location:
                          type: string
                        name:
                          type: string
                        phone:
                          type: string
                        price:
                          type: number
                        rating:
                          type: string
                        review_count:
                          type: string
                        transactions:
                          type: string
                        url:
                          type: string
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: number
                      from:
                        type: number
                      last_page:
                        type: number
                      path:
                        type: string
                      per_page:
                        type: number
                      to:
                        type: number
                      total:
                        type: number
  /business:
    post:
      tags:
        - Business
      summary: Add Business
      description: Add Business
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      alias:
                        type: string
                      title:
                        type: string
                coordinates:
                  type: object
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                
                distance:
                  type: number
                is_closed:
                  type: boolean
                location:
                  type: object
                  properties:
                    address1:
                      type: string
                    address2:
                      type: string
                    address3:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
                    state:
                      type: string
                    zip_code:
                      type: string
                phone:
                  type: string
                price:
                  type: number
                rating:
                  type: string
                review_count:
                  type: string
                transactions:
                  type: string
                url:
                  type: string
                image: 
                  type: string
                  format: byte # base64-encoded file contents 

      responses:
        "200":
          description: Success Create Business
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: "#/components/schemas/Response"
  /business/{BusinessId}:  
    delete:
      tags:
        - Business
      summary: Delete Business
      description: Delete Business
      parameters:
        - in: path
          name: BusinessId
          description: Business Id
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: Success Delete Business
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: "#/components/schemas/Response"
        "400":
          description: Business Not Found
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: "#/components/schemas/Response"
    put:
      tags:
        - Business
      summary: Update Business
      parameters:
        - in: path
          name: BusinessId
          description: Business Id
          required: true
          schema:
            type: integer
      description: Update Business
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      alias:
                        type: string
                      title:
                        type: string
                coordinates:
                  type: object
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                
                distance:
                  type: number
                is_closed:
                  type: boolean
                location:
                  type: object
                  properties:
                    address1:
                      type: string
                    address2:
                      type: string
                    address3:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
                    state:
                      type: string
                    zip_code:
                      type: string
                phone:
                  type: string
                price:
                  type: number
                rating:
                  type: string
                review_count:
                  type: string
                transactions:
                  type: string
                url:
                  type: string
                image: 
                  type: string
                  format: byte # base64-encoded file contents 

      responses:
        "200":
          description: Success Update Business
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: "#/components/schemas/Response"
       
    get:
      tags:
        - Business
      summary: Detail Business
      parameters:
        - in: path
          name: BusinessId
          description: Business Id
          required: true
          schema:
            type: integer
      description: Detail Business
      responses:
        "200":
          description: Detail Business
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        alias:
                          type: string
                        categories:
                          type: array
                          items:
                            type: object
                            properties:
                              alias:
                                type: string
                              title:
                                type: string
                        coordinates:
                          type: object
                          properties:
                            latitude:
                              type: number
                            longitude:
                              type: number
                        display_phone:
                          type: string
                        distance:
                          type: number
                        image_url:
                          type: string
                        is_closed:
                          type: boolean
                        location:
                          type: object
                          properties:
                            address1:
                              type: string
                            address2:
                              type: string
                            address3:
                              type: string
                            city:
                              type: string
                            country:
                              type: string
                            state:
                              type: string
                            zip_code:
                              type: string
                        display_location:
                          type: string
                        name:
                          type: string
                        phone:
                          type: string
                        price:
                          type: number
                        rating:
                          type: string
                        review_count:
                          type: string
                        transactions:
                          type: string
                        url:
                          type: string
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: number
                      from:
                        type: number
                      last_page:
                        type: number
                      path:
                        type: string
                      per_page:
                        type: number
                      to:
                        type: number
                      total:
                        type: number
  
  /category:
    get:
      tags:
        - Category
      summary: List Category
      description: List Category
      responses:
        "200":
          description: Success Get
          content:
            application/json:
              schema:
                type: object
                properties:
                  
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        alias:
                          type: string
                        title:
                          type: integer
                       
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication for API
  schemas:
    Response:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        message:
          type: string
    CreateOrUpdateCategory:
      type: object
      properties:
        name:
          type: string
